name: GuardWolf
main: net.loadingchunks.plugins.GuardWolf.GuardWolf
version: 0.1
commands:
  gw:
    description: GuardWolf Management and Info Commands.
    usage: Type '/gw help' for more information.
  ban:
    description: Ban Hammer
    usage: Type /gw help for a full list of GuardWolf Commands.
  unban:
    description: Pardon your users.
    usage: Type /gw help for a full list of GuardWolf Commands.
  banlist:
    description: View bans for a specific user.
    usage: Type /gw help for a full list of GuardWolf Commands.
  gimp:
    description: Gimp a player, so all they say is random rubbish!
    usage: Type /gw help for a full list of GuardWolf Commands.
  ungimp:
    description: Ungimp a player.
    usage: Type /gw help for a full list of GuardWolf Commands.